name: "Lint"
description: "Lint a service"
inputs:
  access_token:
    description: "A Github Access Token to download private dependencies"
    required: true
  cache_hit:
    description: "A boolean indicating if there was a cache hit"
    required: false
    default: "false"
  lint_command:
    description: "The command to run the linter"
    required: false
    default: "pipenv run make lint"
  python_version:
    description: "Python version to use"
    required: false
    default: "3.7.8"
runs:
  using: "composite"
  steps:
    - name: Add python version to $PATH
      run: echo "::add-path::/opt/hostedtoolcache/Python/${{ inputs.python_version }}/x64/bin"
      shell: bash
    - name: Install pipenv
      run: pip3.7 install -q pipenv
      shell: bash
    - name: Setup Github acces token
      run: sudo git config --global url."https://${{ inputs.access_token}}@github.com/".insteadOf "ssh://git@github.com/"
      shell: bash
    - name: Install dependencies
      run: |
        if [ ${{ inputs.cache_hit }} != 'true' ]; then
          PIPENV_VENV_IN_PROJECT=1 pipenv sync --dev
        fi
      shell: bash
    - name: Run the linter
      run: ${{ inputs.lint_command }}
      shell: bash
